name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rashmikaog
          outputs: |
            dist/github-snake.svg?color_snake=ffffff&color_dots=#333333,#555555,#888888,#aaaaaa,#ffffff
            dist/github-snake-dark.svg?palette=github-dark&color_snake=ffffff&color_dots=#1a1a1a,#2a2a2a,#444444,#666666,#999999

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
          force_orphan: true
